export const FETCH_FAMOUS_PEOPLE = 'FETCH_FAMOUS_PEOPLE';
export const FETCH_FAMOUS_PEOPLE_SUCCESS = 'FETCH_FAMOUS_PEOPLE_SUCCESS';
export const FETCH_MORE_FAMOUS_PEOPLE = 'FETCH_MORE_FAMOUS_PEOPLE';
export const FETCH_MORE_FAMOUS_PEOPLE_SUCCESS = 'FETCH_MORE_FAMOUS_PEOPLE_SUCCESS';
